### ISSUE TITLE
ability to disable duplicate tab check

### ISSUE THREAD

**Issue by blaskovicz** [blaskovicz/tab-polish#19]

**Comment by blaskovicz** [comment]
@lakecityransom can you please try my alpha? I have created a potential PR to address the feature.

I've attached a .zip which can be loaded as an unpacked extension via the guide in the [readme](https://github.com/blaskovicz/tab-polish/blob/master/README.md)
[tab-polish.zip](https://github.com/blaskovicz/tab-polish/files/8454768/tab-polish.zip)
.

**Comment by lakecityransom** [comment]
Hello,

Days after typing that message, I actually found an extension that fully handles window merge/unmerge management. It just wasn't advertised on the cover. Its called tabmanager.io so I started using that. Since I bothered you (sorry) I tested this and it indeed works, for its worth.
